# Generated by Django 4.0.4 on 2022-05-11 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_list', models.JSONField(verbose_name='Lista de productos')),
                ('total_value', models.IntegerField(default=0, verbose_name='Valor total')),
                ('user', models.CharField(max_length=50, verbose_name='Usuario adscrito')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Pedido activo')),
                ('on_delivery', models.BooleanField(default=False, verbose_name='Pedido en camino')),
                ('paid', models.BooleanField(default=False, verbose_name='Pedido pago')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', help_text='Nombre del producto', max_length=50)),
                ('description', models.CharField(default='', help_text='Descripción del producto', max_length=200)),
                ('value', models.IntegerField(default=0, help_text='Precio de venta')),
                ('image_url', models.SlugField(max_length=250, verbose_name='Dirección de imagen')),
                ('qualification', models.IntegerField(choices=[(1, 'Terrible'), (2, 'Yuck'), (3, 'Ok'), (4, 'Yum'), (5, 'Excelent')], verbose_name='Calificación')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.CharField(default='', max_length=250, verbose_name='Dirección')),
                ('user_group', models.IntegerField(choices=[(0, 'Admin'), (1, 'Checker'), (2, 'Delivery'), (3, 'Attendant'), (4, 'Customer')], verbose_name='Grupo')),
                ('active_order', models.JSONField(blank=True, verbose_name='Pedido actual')),
                ('order_story', models.JSONField(blank=True, verbose_name='Historial de pedidos')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
