# Generated by Django 4.0.4 on 2022-05-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='qualification',
            new_name='rating',
        ),
    ]
