# Generated by Django 4.0.4 on 2022-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reviewers',
            field=models.IntegerField(default=0, help_text='Cantidad de reviews'),
        ),
        migrations.AddField(
            model_name='products',
            name='visible',
            field=models.BooleanField(default=True, help_text='Visible en el menu'),
        ),
    ]
