# Generated by Django 4.0.4 on 2022-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_reviewers_products_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='qualification',
            field=models.IntegerField(choices=[(5, 'Excelent'), (4, 'Yum'), (3, 'Regular'), (2, 'Yuk'), (1, 'Ugh')], default=5, help_text='Calificación del producto'),
        ),
    ]
